#!/bin/bash

function cache_stats {
	curl https://corona-stats.online/?source=2 2>/dev/null > ~/.cache/corona || echo "Network Error"
}


case $BLOCK_BUTTON in
	1) cache_stats && notify-send -t 2000 -u low "Corona stats updated" || notify-send -t 2000 -u critical "Something went wrong when updating corona stats" ;;
esac


[ "$(stat -c %y ~/.cache/corona 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
	cache_stats

# Tartunnat (kasvun määrä) | Kuolemat (kasvun määrä)
text=$(grep "Finland" ~/.cache/corona |
	sed "s/\s*//g ; s/│/;/g ; s/║/;/g ; s/║//g" |
	awk -F';' '{print " " $9 " (" $5 ") |  " $6 " (" $7 ")"}' |
	sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" |
	sed 's/ ()//g')

echo $text
