#!/bin/bash

ac_power="$(acpi -a | awk '{print $3}')"
battery_level="$(acpi |awk '{print $4}')"

if [[ "$ac_power" == "off-line" ]]
then
        result="Aikaa jäljellä: $(acpi |awk '{print $5}')"
elif [[ "$battery_level" == "100%" ]]
then
        result="Akku on täysi"
else
        result="Aika kunnes ladattu: $(acpi |awk '{print $5}')"
fi

notify-send -t 2000 -u low "$result"
