#!/bin/bash

title="System"
widthpercent=100

typeset -A menu
menu=(
    [Cancel]=""
    [Suspend]="~/.config/i3/scripts/lockscript"
    [Reboot]="reboot"
    [Shutdown]="shutdown now"
)
menu_nrows=${#menu[@]}

typeset -A colors
colors=(
    [-color-window]="#000000, #ffffff, #ffffff"
    [-color-normal]="#ffffff, #000000, #eee8d5, #272727, #ffffff"
    [-color-active]="#fdf6e3, #268bd2, #eee8d5, #268bd2, #fdf6e3"
    [-color-urgent]="#fdf6e3, #dc322f, #eee8d5, #dc322f, #fdf6e3"
)
